### ISSUE TITLE
1.8 still don't work

### ISSUE THREAD

**Issue by Krormar** [xiaoye97/CoreKeeperAutoFish#8]
Hey! Thanks for fast update, but its plugin still dont work for me! Here is a messange I get in console then I try to run it. If it change anything take a note that Im using Thunderstore Mod Maganer. Below I have log from trying to run game with plugins

[LogOutput.log](https://github.com/xiaoye97/CoreKeeperAutoFish/files/10687753/LogOutput.log)

**Comment by xiaoye97** [comment]
Since version 1.7, this mod depends on CoreLib. I forgot to fill in the dependency information in Thunderstore. I will add this information later.

**Comment by Mithalogica** [comment]
Curious about BucketMod, since this is where I land when I follow the link on the mod page; but Thunderstore still lists version 1.0.0, updated a month ago. I can (now) get the game to launch with both PLacement Plue and Bucket Mod enabled, but the table/buckets are nowhere to be crafted. If I recall, one of the new vanilla items took the same crafting slot, perhaps?
